## Download file and sort through initial columns

In [98]:
# importing panda library
import pandas as pd
  
# readinag given csv file
# and creating dataframe
df = pd.read_csv("Metazygia monitor 1.txt", delimiter = "\t")

# adding column headings
#df.columns = ['Index', 'Date', 'Time']
'folder/subfolder/out.csv'  
# store dataframe into csv file
df.to_csv('Metazygia monitor 1.csv', index = None)
dfcsv = pd.read_csv("Metazygia monitor 1.csv")

In [99]:

df1 = dfcsv.iloc[:, 1:3] 
df1 = df1.join(dfcsv.iloc[:, -33:])


columns_names = [ 'Date', 'Time', 'lights',
'Monitor 1 Spider 1', 'Monitor 1 Spider 2', 'Monitor 1 Spider 3', 'Monitor 1 Spider4', 'Monitor 1 Spider5', 'Monitor 1 Spider6', 'Monitor 1 Spider7', 'Monitor 1 Spider8', 'Monitor 1 Spider9', 'Monitor 1 Spider10', 'Monitor 1 Spider11', 'Monitor 1 Spider12', 
'Monitor 1 Spider13', 'Monitor 1 Spider14','Monitor 1 Spider15', 'Monitor 1 Spider16', 'Monitor 1 Spider17', 'Monitor 1 Spider18', 'Monitor 1 Spider19', 'Monitor 1 Spider20', 'Monitor 1 Spider21', 'Monitor 1 Spider22', 'Monitor 1 Spider23',
'Monitor 1 Spider24', 'Monitor 1 Spider25', 'Monitor 1 Spider26', 'Monitor 1 Spider27', 'Monitor 1 Spider28', 'Monitor 1 Spider29', 'Monitor 1 Spider30', 'Monitor 1 Spider31', 'Monitor 1 Spider32',]

df1.columns = columns_names
#df1 = dfcsv.drop[:, 4:]
#display(dfcsv)
display(df1)

,Date,Time,lights,Monitor 1 Spider 1,Monitor 1 Spider 2,Monitor 1 Spider 3,Monitor 1 Spider4,Monitor 1 Spider5,Monitor 1 Spider6,Monitor 1 Spider7,...,Monitor 1 Spider23,Monitor 1 Spider24,Monitor 1 Spider25,Monitor 1 Spider26,Monitor 1 Spider27,Monitor 1 Spider28,Monitor 1 Spider29,Monitor 1 Spider30,Monitor 1 Spider31,Monitor 1 Spider32
0,20 Apr 17,16:47:00,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,20 Apr 17,16:48:00,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,20 Apr 17,16:49:00,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,20 Apr 17,16:50:00,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,20 Apr 17,16:51:00,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21039,5 May 17,07:26:00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21040,5 May 17,07:27:00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21041,5 May 17,07:28:00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21042,5 May 17,07:29:00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21043,5 May 17,07:30:00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [100]:
DateTime = df1['Date'].astype(str) + ' '+ df1['Time']
df1.insert(0, "Date-Time", DateTime)
#df1 = df1.set_index('Date-Time')
df1 = df1.drop(['Date', 'Time'], axis = 1)
#df1.head()

In [101]:
display(df1)

,Date-Time,lights,Monitor 1 Spider 1,Monitor 1 Spider 2,Monitor 1 Spider 3,Monitor 1 Spider4,Monitor 1 Spider5,Monitor 1 Spider6,Monitor 1 Spider7,Monitor 1 Spider8,...,Monitor 1 Spider23,Monitor 1 Spider24,Monitor 1 Spider25,Monitor 1 Spider26,Monitor 1 Spider27,Monitor 1 Spider28,Monitor 1 Spider29,Monitor 1 Spider30,Monitor 1 Spider31,Monitor 1 Spider32
0,20 Apr 17 16:47:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,20 Apr 17 16:48:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,20 Apr 17 16:49:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,20 Apr 17 16:50:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,20 Apr 17 16:51:00,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21039,5 May 17 07:26:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21040,5 May 17 07:27:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21041,5 May 17 07:28:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21042,5 May 17 07:29:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21043,5 May 17 07:30:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [102]:
df1.to_csv('Metazygia monitor 1.csv', index = None)