## Download file and sort through initial columns

In [1]:
# importing panda library
import pandas as pd
import numpy as np
  
# readinag given csv file
# and creating dataframe
df = pd.read_csv("Metazygia monitor 1.txt", delimiter = "\t")

# adding column headings
#df.columns = ['Index', 'Date', 'Time']
#'folder/subfolder/out.csv'  
# store dataframe into csv file
df.to_csv('Metazygia monitor 1.csv', index = None)
dfcsv = pd.read_csv("Metazygia monitor 1.csv")

In [2]:
#Function to drop incomplete days from the data set
def wholedays(df):
    start = df.index[df['Time']=='00:00:00']
    end=df.index[df['Time']=='23:59:00']
    newdf=df[start[0]:(end[-1]+1)]
    return newdf

#Funtion to set the index as the Date and Time
def setindex(df):
    df['Date_Time']=pd.to_datetime(df['Date'] + ' ' + df['Time'])
    df = df.set_index(pd.DatetimeIndex(df['Date_Time']))
    df = df.drop(['Date', 'Time'], axis = 1)
    return df

#Funtion to convert txt file to csv file
def txt_to_csv(txt):
    df=pd.read_csv(txt+'.txt',delimiter = "\t")
    df.to_csv(txt+'.csv', index = None)
    dfcsv = pd.read_csv(str(txt)+'.csv')
#Dropping random empty columns
    df1 = dfcsv.iloc[:, 1:3] 
    df1 = df1.join(dfcsv.iloc[:, -33:])
#Create column names for each spider
    columns=[]
    for i in range(0,32):
        columns.append('Monitor 1 Spider '+str(i+1))
    columns_names = [ 'Date', 'Time', 'lights']
    column_names=np.concatenate((columns_names, columns))
    df1.columns = column_names
#Run functions to drop incomplete days and set index
    df1=wholedays(df1)
    df1=setindex(df1)
    return(df1)
    
df1 = txt_to_csv('Metazygia monitor 1')
df1.to_csv('Metazygia monitor 1.csv')
display(df1)

,lights,Monitor 1 Spider 1,Monitor 1 Spider 2,Monitor 1 Spider 3,Monitor 1 Spider 4,Monitor 1 Spider 5,Monitor 1 Spider 6,Monitor 1 Spider 7,Monitor 1 Spider 8,Monitor 1 Spider 9,...,Monitor 1 Spider 24,Monitor 1 Spider 25,Monitor 1 Spider 26,Monitor 1 Spider 27,Monitor 1 Spider 28,Monitor 1 Spider 29,Monitor 1 Spider 30,Monitor 1 Spider 31,Monitor 1 Spider 32,Date_Time
Date_Time,,,,,,,,,,,,,,,,,,,,,
2017-04-21 00:00:00,0,0,0,0,0,1,3,0,0,3,...,0,0,0,0,2,5,0,0,0,2017-04-21 00:00:00
2017-04-21 00:01:00,0,0,0,0,0,0,9,0,0,16,...,0,0,0,0,5,10,0,0,0,2017-04-21 00:01:00
2017-04-21 00:02:00,0,0,0,0,0,7,2,0,0,10,...,2,0,0,4,4,4,0,0,0,2017-04-21 00:02:00
2017-04-21 00:03:00,0,0,0,0,0,6,0,0,0,0,...,0,0,0,0,5,4,0,0,0,2017-04-21 00:03:00
2017-04-21 00:04:00,0,0,0,0,2,2,0,0,0,2,...,0,0,0,0,3,2,0,0,0,2017-04-21 00:04:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-05-04 23:55:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2017-05-04 23:55:00
2017-05-04 23:56:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2017-05-04 23:56:00
2017-05-04 23:57:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2017-05-04 23:57:00
2017-05-04 23:58:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2017-05-04 23:58:00
2017-05-04 23:59:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2017-05-04 23:59:00

In [3]:
min_day=1440
total_time = len(df.index)
num_days = total_time//min_day

#Split DataFrame into LD and DD DataFrames
def LDandDD(df):
    #Run for loop to check the light activity of each day
    for i in range(0,num_days):
        dfnew=df[min_day*(i):min_day*(i+1)]
        dfnew=dfnew.reset_index(drop=True)
        #Find the first day of the DD cycle. This is where we will split the 
        #DataFrame
        if np.mean(dfnew.lights)==0:
            end=min_day*i
            break
    LDdf=df1.iloc[:end]
    DDdf=df1.iloc[end:]
    return LDdf, DDdf

LDdf, DDdf = LDandDD(df1)
LDdf.to_csv('Metazygia monitor 1_LD.csv')
DDdf.to_csv('Metazygia monitor 1_DD.csv')